Vagrant.configure("2") do |config|
  config.vm.define "desafio" do |desafio|
    desafio.vm.box = "ubuntu/focal64"
  end

  # Habilitar el reenvío de puerto
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Configuración del proveedor VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.name = "desafio"
    vb.memory = "6144"
    vb.cpus = 4
  end

  # Ejecutar el script de bootstrap para instalar aplicaciones
  config.vm.provision "shell", path: "bootstrap.sh"
end
